name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=2.0.3
  - pip=23.2.1
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.15.12